import LeanJax.Types
/-! MLIR (StableHLO) code generator: emit MLIR modules from NetSpec.

    MLP-only for now (`.dense` with `.relu` or `.identity`). Emits a single
    `@forward` function that takes x and interleaved (W_i, b_i) params and
    returns the final logits. Batch size is static. -/

namespace MlirCodegen

/-- Infer the input feature dim from the first dense layer. -/
private def inputDim (spec : NetSpec) : Nat :=
  match spec.layers.head? with
  | some (.dense fanIn _ _) => fanIn
  | _ => spec.imageH * spec.imageW

/-- Render a StableHLO tensor type, e.g. `tensor<128x784xf32>`. -/
private def tensorTy (dims : List Nat) : String :=
  "tensor<" ++ String.intercalate "x" (dims.map toString) ++ "xf32>"

/-- Sanitize a string for use as an MLIR identifier. -/
private def sanitize (s : String) : String :=
  s.toLower.map (fun c => if c.isAlphanum then c else '_')

/-- Emit the body of the forward function: one block per dense layer. -/
private def emitForwardBody (spec : NetSpec) (batchSize : Nat) : String := Id.run do
  let mut code : String := ""
  let mut curSSA : String := "%x"
  let mut curDim : Nat := inputDim spec
  let mut idx : Nat := 0
  for l in spec.layers do
    match l with
    | .dense fanIn fanOut act =>
      let bTy := tensorTy [batchSize, fanOut]
      -- matmul: curSSA @ W_idx  (batch × fanIn) @ (fanIn × fanOut) -> (batch × fanOut)
      code := code ++ s!"    %mm{idx} = stablehlo.dot_general {curSSA}, %W{idx},\n" ++
        "              contracting_dims = [1] x [0],\n" ++
        "              precision = [DEFAULT, DEFAULT]\n" ++
        s!"            : ({tensorTy [batchSize, fanIn]}, {tensorTy [fanIn, fanOut]}) -> {bTy}\n"
      -- broadcast bias (fanOut,) -> (batch, fanOut)
      code := code ++ s!"    %bb{idx} = stablehlo.broadcast_in_dim %b{idx}, dims = [1]\n" ++
        s!"           : ({tensorTy [fanOut]}) -> {bTy}\n"
      -- add
      code := code ++ s!"    %ab{idx} = stablehlo.add %mm{idx}, %bb{idx} : {bTy}\n"
      -- activation
      match act with
      | .relu =>
        code := code ++ s!"    %z{idx} = stablehlo.constant dense<0.0> : {bTy}\n"
        code := code ++ s!"    %h{idx} = stablehlo.maximum %ab{idx}, %z{idx} : {bTy}\n"
        curSSA := s!"%h{idx}"
      | .identity =>
        curSSA := s!"%ab{idx}"
      | .relu6 =>
        code := code ++ s!"    // UNSUPPORTED activation: relu6 (not needed for MLP)\n"
        curSSA := s!"%ab{idx}"
      curDim := fanOut
      idx := idx + 1
    | _ =>
      code := code ++ "    // UNSUPPORTED LAYER — MLP codegen only handles .dense\n"
  code := code ++ s!"    return {curSSA} : {tensorTy [batchSize, curDim]}\n"
  pure code

/-- Emit the forward function signature with interleaved (W_i, b_i) params. -/
private def emitForwardSig (spec : NetSpec) (batchSize : Nat) : String := Id.run do
  let inDim := inputDim spec
  let mut params : String := s!"%x: {tensorTy [batchSize, inDim]}"
  let mut outDim : Nat := inDim
  let mut idx : Nat := 0
  for l in spec.layers do
    match l with
    | .dense fanIn fanOut _ =>
      params := params ++ s!",\n    %W{idx}: {tensorTy [fanIn, fanOut]}, %b{idx}: {tensorTy [fanOut]}"
      outDim := fanOut
      idx := idx + 1
    | _ => pure ()
  pure s!"func.func @forward(\n    {params}\n  ) -> {tensorTy [batchSize, outDim]}"

/-- Generate a StableHLO MLIR module for an MLP `NetSpec`. -/
def generate (spec : NetSpec) (batchSize : Nat) : String :=
  s!"// {spec.name} — Generated by Lean 4 → MLIR (StableHLO)\n" ++
  s!"// Batch size: {batchSize}\n\n" ++
  s!"module @{sanitize spec.name} " ++ "{\n" ++
  "  " ++ emitForwardSig spec batchSize ++ " {\n" ++
  emitForwardBody spec batchSize ++
  "  }\n" ++
  "}\n"

end MlirCodegen
